name: tfsec scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tfsec:
    name: Run tfsec 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash          

      - name: Run tfsec
        run: mkdir -p scan-results tfsec . > scan-results/tfsec-output.txt